### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by lyq893** [niujinshuchong/SalGan_pytorch#1]
Thank you for your share!

When I ran the code, I encountered this error. Do you have any solution?

Traceback (most recent call last):
  File "vggnet.py", line 235, in <module>
    gan.load_state_dict(torch.load('GAN_model/gan_torch_model.pkl'))
  File "/icislab/volume1/lyq/anaconda3/envs/SalGan_pytorch/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/icislab/volume1/lyq/anaconda3/envs/SalGan_pytorch/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

Can you give me some advice?

**Comment by niujinshuchong** [comment]
@lyq893 I think you could try pytorch 0.4 and python 2.7.

**Comment by lyq893** [comment]
@niujinshuchong  I still can't do this. why?

**Comment by niujinshuchong** [comment]
@lyq893 I just test on pytorch1.1.0 and python 3.7.3. The model can be loaded. 

Do you download the model and save it under GAN_model folder?

**Comment by lyq893** [comment]
@niujinshuchong yes,I have downloaded and saved.
and My environment is pytorch1.3.1 and python 3.7.5.
Still reporting this error.

**Comment by niujinshuchong** [comment]
@lyq893 The size of the model is about 122M. Maybe you can check whether it's downloaded completely.

**Comment by lyq893** [comment]
Thanks very much.
The reason is that the model file I downloaded is incomplete.

Thank you very much for helping me solve the problem.
