### ISSUE TITLE
 IOError: [Errno 2] No such file or directory: 'GAN_model/gan_torch_model.pkl'

### ISSUE THREAD

**Issue by lyq893** [niujinshuchong/SalGan_pytorch#2]
Hi, 
What's wrong with this error that I keep reporting?
 I tried various paths and I couldn't find the file.

(SalGan_pytorch) lyq@sdnu-SYS-4028GR-TR:/icislab/volume1/lyq/codes/SalGan_pytorch-master$ python vggnet.py
Traceback (most recent call last):
  File "vggnet.py", line 235, in <module>
    gan.load_state_dict(torch.load('GAN_model/gan_torch_model.pkl'))
  File "/icislab/volume1/lyq/anaconda3/envs/SalGan_pytorch/lib/python2.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'GAN_model/gan_torch_model.pkl'

![image](https://user-images.githubusercontent.com/55521679/71663344-c95b5280-2d8f-11ea-86b4-1e317d607b3b.png)

Can you give me some suggestions？

**Comment by niujinshuchong** [comment]
You need to download the file.

**Comment by lyq893** [comment]
Thank you for helping me！

What other files do I need to download? I have put that model file in the directory.

**Comment by niujinshuchong** [comment]
From the screenshot, I guess your filename is not correct. There is a space in your filename (" ".pkl)
